name: 'docsify-file-generate-slidebar'
description: 'auto generate _sidebar for docsify'
inputs:
  github_token:
    description: 'github_token'
    required: true
  include:
    description: 'include target files for _sidebar by regular expression'
    default: '.*\.md$'
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: action.sh . ${{ inputs.include }} > _sidebar.md
      shell: bash
    - name: commit
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add _sidebar.md
        status=$(git status --porcelain)
        if [ -z "$status" ]; then
          echo "There are changes"
        else
          git commit -m "Add changes"
        fi
      shell: bash
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}

branding:
  icon: 'bookmark'
  color: 'green'